// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PRheileuXS_m9er3LYh9bwjioaJRuHY',
    appId: '1:159421512119:web:fa869d65379db9bc24d032',
    messagingSenderId: '159421512119',
    projectId: 'dating-app-58efd',
    authDomain: 'dating-app-58efd.firebaseapp.com',
    databaseURL: 'https://dating-app-58efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dating-app-58efd.firebasestorage.app',
    measurementId: 'G-CHWCK040E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCQrWhvPK13sl_gmMCO--_lTvUUMnyWS8',
    appId: '1:159421512119:android:217f8c248fbf437224d032',
    messagingSenderId: '159421512119',
    projectId: 'dating-app-58efd',
    databaseURL: 'https://dating-app-58efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dating-app-58efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaoiCvF18IDi4ZayCrhRWCcN6qFPOGTuQ',
    appId: '1:159421512119:ios:5ec5bcadb4ff121b24d032',
    messagingSenderId: '159421512119',
    projectId: 'dating-app-58efd',
    databaseURL: 'https://dating-app-58efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dating-app-58efd.firebasestorage.app',
    iosClientId: '159421512119-i5h88k574k4f9edn3bpgt81cvmj2i9v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaoiCvF18IDi4ZayCrhRWCcN6qFPOGTuQ',
    appId: '1:159421512119:ios:5ec5bcadb4ff121b24d032',
    messagingSenderId: '159421512119',
    projectId: 'dating-app-58efd',
    databaseURL: 'https://dating-app-58efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dating-app-58efd.firebasestorage.app',
    iosClientId: '159421512119-i5h88k574k4f9edn3bpgt81cvmj2i9v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1PRheileuXS_m9er3LYh9bwjioaJRuHY',
    appId: '1:159421512119:web:a36da3b46db32c8e24d032',
    messagingSenderId: '159421512119',
    projectId: 'dating-app-58efd',
    authDomain: 'dating-app-58efd.firebaseapp.com',
    databaseURL: 'https://dating-app-58efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dating-app-58efd.firebasestorage.app',
    measurementId: 'G-3ZT6RKBYZS',
  );
}
